// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoh1hySDzh1eIHUXlCqxWxvopx5QtOEjY',
    appId: '1:1091996547788:web:2b0bcb149c7b736558e069',
    messagingSenderId: '1091996547788',
    projectId: 'campus-connect-f2e24',
    authDomain: 'campus-connect-f2e24.firebaseapp.com',
    storageBucket: 'campus-connect-f2e24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY2fl9Yj04vDgf93ycXqgL5ZjMNi34sjQ',
    appId: '1:1091996547788:android:a1c21219cb107a3758e069',
    messagingSenderId: '1091996547788',
    projectId: 'campus-connect-f2e24',
    storageBucket: 'campus-connect-f2e24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEGoa07ZwM-KZ1Q8vjeAGxf7Ebf7XK4Qc',
    appId: '1:1091996547788:ios:0f600760635ddde558e069',
    messagingSenderId: '1091996547788',
    projectId: 'campus-connect-f2e24',
    storageBucket: 'campus-connect-f2e24.appspot.com',
    iosBundleId: 'com.example.campusConnecy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEGoa07ZwM-KZ1Q8vjeAGxf7Ebf7XK4Qc',
    appId: '1:1091996547788:ios:0f600760635ddde558e069',
    messagingSenderId: '1091996547788',
    projectId: 'campus-connect-f2e24',
    storageBucket: 'campus-connect-f2e24.appspot.com',
    iosBundleId: 'com.example.campusConnecy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoh1hySDzh1eIHUXlCqxWxvopx5QtOEjY',
    appId: '1:1091996547788:web:1693a4022dd9109558e069',
    messagingSenderId: '1091996547788',
    projectId: 'campus-connect-f2e24',
    authDomain: 'campus-connect-f2e24.firebaseapp.com',
    storageBucket: 'campus-connect-f2e24.appspot.com',
  );
}
